### PR TITLE
Php 7 and other environments

### PR DESCRIPTION
**Pull request by Gisleburt**
Gets PHP 7 and Nightly working in Travis.

### CODE REVIEW

**Comment by Gisleburt** [comment]
I'm a bit stuck with the HHVM bug. On my local, test number 65 also fails... but it's a different test.

**Travis-CI**
```
$ vendor/bin/phpunit
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/travis/build/moodev/bounce/phpunit.xml

........................................F........................ 65 / 93 ( 69%)
............................

Time: 4.25 seconds, Memory: 16.78Mb
There was 1 failure:
1) MooDev\Bounce\Proxy\LookupMethodProxyGeneratorTest::testProxyGenerationNoMethodsExistingConstructor
Failed asserting that 1 matches expected 4.

/home/travis/build/moodev/bounce/tests/MooDev/Bounce/Proxy/LookupMethodProxyGeneratorTest.php:40

FAILURES!
Tests: 93, Assertions: 227, Failures: 1.
```
**local (Docker)**
```
$ docker run -itv `pwd`:/tmp/app -w /tmp/app hhvm/hhvm vendor/bin/phpunit
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /tmp/app/phpunit.xml

...........................................F..................... 65 / 93 ( 69%)
............................

Time: 10.99 seconds, Memory: 22.30Mb

There was 1 failure:

1) MooDev\Bounce\Proxy\Store\UniqTmpDirFilesystemProxyStoreTest::testStoreAndImport
Failed asserting that file "/tmp/bounce_jYBifg/a" does not exist.

/tmp/app/tests/MooDev/Bounce/Proxy/Store/UniqTmpDirFilesystemProxyStoreTest.php:18

FAILURES!
Tests: 93, Assertions: 242, Failures: 1.
```
Note: I didn't run `composer install` with the container which may also have an impact.

**Comment by Gisleburt** [comment]
Additionally, running _just_ the test that fails in Travis on my docker container passes.
```
$ docker run -itv `pwd`:/usr/local/app -w /usr/local/app hhvm/hhvm vendor/bin/phpunit tests/MooDev/Bounce/Proxy/LookupMethodProxyGeneratorTest.php 
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /usr/local/app/phpunit.xml

...

Time: 6.51 seconds, Memory: 11.06Mb

OK (3 tests, 42 assertions)
```

**Comment by JonathanO** [comment]
I gave up with the HHVM failures, it doesn't seem that HHVM is particularly complete or consistent with PHP around the Reflection interfaces, and it's changing rapidly. I'm guessing the version of HHVM being run by Travis has a bug that your local version doesn't.

That does not exist assertion failure is probably a difference in HHVM GC and destructor behaviour vs PHP. PHP requires that __destruct is called as soon as the refcount for an object hits 0, and that test assumes that behaviour. I'm guessing that HHVM doesn't mirror that behaviour, and wont call __destruct until the next GC pass...

It's probably not the end of the world to remove that assertion. That store type is only used for testing (it's pretty useless for anything else), so introducing a bug that breaks cleanup on destruct would be merely annoying.

**Comment by Gisleburt** [comment]
We could also call the GC manually, but that would have a serious performance impact. I'll merge this PR (since it resolves the build for PHP 7 and nightly) and create a new issue for HHVM.

**Pull request merged**
